services:
  seq:
    image: datalust/seq:latest
    container_name: ddev-${DDEV_SITENAME}-seq
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    # expose:
    #   - "80"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=5340:80
      - HTTPS_EXPOSE=5341:80
      - ACCEPT_EULA=Y