name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env:
          - { TYPO3: '12.4' , PHP: '8.1'}
          - { TYPO3: '12.4' , PHP: '8.2'}
          - { TYPO3: '12.4' , PHP: '8.3'}
          - { TYPO3: '12.4' , PHP: '8.4'}
          - { TYPO3: '13.4' , PHP: '8.2'}
          - { TYPO3: '13.4' , PHP: '8.3'}
          - { TYPO3: '13.4' , PHP: '8.4'}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.env.PHP }}
          extensions: zip, pdo_sqlite, opentelemetry
          coverage: none

      - name: Install dependencies
        run: composer update --with "typo3/cms-core:^${{matrix.env.TYPO3}}"

      - name: Run tests
        run: composer ci:tests:unit
